config/routes.rb
Rails.application.routes.draw do
  get 'company/index'

  get 'resources/index'

  resources :presses

  # route the site root to home index
  root :to => 'home#index'

  match '/', :to => "home#index", :as => :home_index, :via => :get
  match '/home', :to => "home#home", :as => :home, :via => :get

  match '/resources', :to => "resources#index", :as => :resources, :via => :get

  match '/about/board', :to => "company#board", :as => :board, :via => :get

end

app/models/press.rb
#require 'press_uploader'

class Press
  include Mongoid::Document

  field :title, type: String
  field :summary, type: String
  field :url, type: String
 # field :logo_image_name, type: String
 # mount_uploader :logo, PressUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def get_header
    require 'nokogiri'
    require 'open-uri'

    page = Nokogiri::HTML(open("http://www.solidfire.com/"))
    page.css("header").text
  end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def index
  end

  def board
    set_meta_tags :title => 'SolidFire | Our Board',
                  :description => 'SolidFire Board of Directors bring a combined 150 years of technologically-focused entrepreneurial spirit to the SolidFire team.',
                  :canonical => 'http://www.solidfire.com/about/board/'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    I18n.locale = params[:locale] || I18n.default_locale

    set_meta_tags :title => t('controllers.home.title'),
                  :description => t('controllers.home.description'),
                  :meta => t('controllers.home.meta')
  end

  def home

  end
end

app/controllers/presses_controller.rb
class PressesController < ApplicationController
  before_action :set_press, only: [:show, :edit, :update, :destroy]

  # GET /presses
  def index
    @presses = Press.all
  end

  # GET /presses/1
  def show
  end

  # GET /presses/new
  def new
    @press = Press.new
  end

  # GET /presses/1/edit
  def edit
  end

  # POST /presses
  def create
    @press = Press.new(press_params)

    # uploader = PressUploader.new

    # uploader.store!(params[:press][:logo])

    removeFileExtension = params[:press][:logo_image_name][0..-5]

    Cloudinary::Uploader.upload(params[:press][:logo], :public_id => 'press/' + removeFileExtension)

    if @press.save
      redirect_to @press, notice: 'Press was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /presses/1
  def update
    if @press.update(press_params)
      redirect_to @press, notice: 'Press was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /presses/1
  def destroy
    @press.destroy
    redirect_to presses_url, notice: 'Press was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_press
      @press = Press.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def press_params
      params.require(:press).permit(:title, :summary, :url, :logo_image_name)
    end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  def get_sf_header
    require 'nokogiri'
    require 'open-uri'

    page = Nokogiri::HTML(open("http://www.solidfire.com/"))
    page.css("footer")
  end

  def index
    @get_header_new = get_sf_header
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/presses_helper.rb
module PressesHelper
end

app/helpers/resource_helper.rb
module ResourceHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/views/company/board.html.haml
#board
  .container
    .full-row
      %h1 Board of Directors
    .full-row
      %h3 Dave Wright
      %p
        = image_tag 'company/davewrightbw115.jpg', :align => 'left'
        Dave Wright left Stanford in 1998 to help start GameSpy Industries, a leader in online video game media, technology, and software. While at GameSpy, Dave led the team that created a backend infrastructure powering thousands of games and millions of gamers. GameSpy merged with IGN Entertainment in 2004 to create one of the largest Internet gaming & entertainment media companies.  Dave served as Chief Architect for IGN and lead technology integration with FIM / MySpace after IGN was acquired by NewsCorp in 2005.
      %p
        In 2007 Dave founded Jungle Disk, a pioneer and early leader in cloud-based storage and backup solutions for consumers and businesses.  Jungle Disk was acquired by leading cloud provider Rackspace in 2008 and Dave worked closely with the Rackspace Cloud division to build a cloud platform supporting tens of thousands of customers. In December 2009 Dave left Rackspace to start SolidFire.
      %hr
      %h3 Bill Chambers
      %p
        = image_tag 'company/bill1.jpg', :align => 'left'
        Bill Chambers specializes in creating and developing markets for innovative storage technologies. Bill has more than 20 years of executive and management experience at high technology startups and Fortune 500 companies. This includes serving as vice president of the LeftHand Networks Division in the HP StorageWorks organization.
      %p
        Bill founded and served as the president and CEO of LeftHand Networks prior to its acquisition by HP. He led the company through three rounds of successful venture financing and development of the storage industry's first IP SAN solution. Prior to Bill's LeftHand Networks experience, he held leadership roles including President and CEO of GE Fanuc Asia Pacific, a joint venture between General Electric Inc. and Fanuc Ltd. of Japan.Currently, Bill is serving on the SolidFire Board of Directors. SolidFire, is a provider of all-solid-state (SSD) primary storage systems for cloud service providers.
      %hr
      %h3 Ron Bernal
      %p
        = image_tag 'company/ron_bernal.jpg', :align => 'left'
        Ron joined NEA in 2010 as a Venture Partner and focuses on information technology and alternative energy technology investments. Prior to joining NEA, Ron was a Partner at Sequel Venture Partners where he focused on cleantech, enterprise infrastructure and enterprise software investments. While at Sequel, he led the firm's investments in HelioVolt and Buzzwire. Ron previously served as a Venture Partner at Sutter Hill Ventures, where he led the firm's investments in Data Domain, Drobo, ProStor, LifeSize, Indicative and Redseal Systems. Prior to joining Sutter Hill Ventures, Ron worked for Cisco Systems as Vice President of Operations for the Product Technology Groups and the Service Provider Line of Business. He joined Cisco following the acquisition of Growth Networks in 2000, where he was President and CEO. Ron co-founded Growth Networks, a fabless Internet switching fabric semiconductor company, in 1998 while serving as an entrepreneur-in-residence at NEA. Prior to working with NEA, he spent more than seven years with Silicon Graphics, Inc. (SGI) in roles of increasing responsibility, including Senior Vice president and General Manager of the $1 billion-plus server division and President of the MIPS group, the microprocessor subsidiary of SGI. Ron was also Vice President of Engineering and COO of Edge Computer, a computer company he co-founded in 1983.
      %p
        A strong advocate of alternative energy technologies, Ron is a founding member and chairman of the Colorado Cleantech Industry Association and serves on the Colorado School of Mines Advisory, Colorado State University Ventures and NREL VC advisory boards. He holds a bachelor's degree in electrical engineering from DeVry Institute of Technology.
      %hr
      %h3 Art Marks
      %p
        = image_tag 'company/MarksIMGSmall.JPG', :align => 'left'
        Art Marks received his first email address in 1979 while working at GE Information Systems.  Since switching to venture capital in 1984, he has enjoyed working with new technologies and entrepreneurs.  Art has practiced both the art and science of venture capital for nearly 30 years.  He regards entrepreneurs as modern day heroes.
      %p
        Art's present company responsibilities include Domain Holdings, EnterpriseDB, Jumptap, Parature, SafeNet, SolidFire, Videology (f.k.a. TidalTV), and Vubiquity (f.k.a. Avail-TVN).  He is involved in media, Internet marketing, IT infrastructure and security-related companies. He is currently on the board of Venture Philanthropy Partners.  He is a member of the University of Michigan Engineering Advisory Council as well as the Stanford Law School Board of Visitors.
      %p
        Art is a student and teacher of entrepreneurial CEOs.  Prior to Valhalla, Art was a general partner at New Enterprise Associates (NEA).  He joined NEA in 1984 as a General Partner with the launch of NEA III and was active there through NEA X.  He was responsible for creating NEA's technology practice and was directly involved in over 60 portfolio company investments while at NEA.
      %p
        Prior to his role at NEA, Art held several significant operating positions at General Electric.  He served as the General Manager of X-Ray products at General Electric's Medical Systems division and as Senior Vice President of GE Information Services (GEIS).  He was also President of the Software Products Operation of GEIS. Prior to General Electric, Art held several marketing, sales and finance positions at Baxter Laboratories.
      %p
        Art received a Masters in Business Administration with high distinction (Baker Scholar) from the Harvard University Graduate School of Business and a Bachelor of Science in Industrial Engineering from the University of Michigan.
      %p
        Past investments include Advertising.com (AOL), Intersolv (MERANT), Clarify, eXcelon, Amisys (HBOC), ATML (Virata), InSoft (Netscape), IndusRiver Networks (Enterasys), Call Technologies (3Com), Progress Software, Trilogy, Inc., and WNP Communications (NextLink).
      %p
        Art, his wife and children reside in Potomac, Maryland.  He enjoys fly-fishing, sailing, military history and golf.  The best way to reach him is by email.
      %hr
      %h3 Harry Weller
      %p
        = image_tag 'company/harryweller.jpg', :align => 'left'
        Harry focuses on early stage consumer, enterprise and energy technology investing. He is frequently recognized as one of America's top venture capitalists with recent honors including the Forbes "Midas List", Washingtonian's "Titans of Technology" and Business Insider's "Top 5 East Coast VCs".
      %p
        Prior to joining NEA, Harry was a Partner at FBR Technology Venture Partners where he learned the costs and benefits of a bubble! Early in his career, Harry managed  technology initiatives in the energy, financial and telecommunications industries with several consulting firms including the Boston Consulting Group. Prior to his business career, Harry served as an aviator in the U.S. Navy. Harry received his MBA from Harvard Business School and his bachelor's degree in Physics from Duke University.
      %p
        Harry serves on the board of the Mid-Atlantic Venture Association (MAVA), is a past Chairman of MAVA Capital Connection, and co-founded the Young Mid-Atlantic Venture Association (YAVA).
      %hr
      %h3 Phil Bronner
      %p
        = image_tag 'company/bio_bronner_2.jpg', :align => 'left'
        Philip Bronner joined Novak Biddle Venture Partners in 1999 and is focused on investments in information technology. Prior to joining Novak Biddle he founded a media technology company, and served as a management consultant with McKinsey & Co. in New York. He  advised high-tech clients on corporate strategy and worked as a software engineer at IBM.
      %p
        Phil has been named one of Washington, D.C. area's 100 "Tech Titans". Phil earned a BS in Computer Science from Carnegie Mellon University; a Juris Doctorate from the University of Pennsylvania's School of Law; and a Master of Business Administration from the Wharton School at the University of Pennsylvania.
      %p
        Phil currently serves on the Alumni Advisory Board for Carnegie Mellon's School of Computer Science and is a board member for In2Books, a Washington, DC-based reading and literacy program.
      %hr
      %h3 Jay Chong
      %p
        = image_tag 'company/jaychongsm1.jpg', :align => 'left'
        Jay joined Samsung Ventures, the investment arm of Samsung Group, in 2010 after spending 10 years at Intel in various marketing and business development roles. He launched multiple mobility products such as the second generation Centrino, Pentium M, and Pentium 4-M and also managed APAC PC accounts and executive relationships. During his final three years at Intel he was on an assignment in Shanghai, China, leading Intel's corporate strategy of incubating local PC OEMs and ODMs. He built a business development team and provided marketing, engineering, and strategy supports to help the local PC OEMs and ODMs to grow their core competencies. Before Intel he lead a sales team at International Rectifier in Korea, developing new businesses in telecommunication, consumer electronics, and automotive. At Samsung Ventures he has invested in SeaMicro (acquired by AMD), Tilera, Raydiance, and NextIO in addition to SolidFire. Jay received his BS in Mechanical Engineering from UC Berkeley and MBA from the Johnson Graduate School of Management at Cornell.
      %hr

app/views/company/index.html.haml
%h1 Company#index
%p Find me in app/views/company/index.html.haml

app/views/home/home.html.haml
.container
  %h1 The 10 column complex nested grid AG test
  .ag.ag1
    %h2 AG1

  .ag.ag2
    %h2 AG 2
    .ag.ag4
      %h2 AG 4
    .ag.ag5
      %h2 AG 5
    .ag.ag6
      %h2 AG 6

    .ag.ag7
      %h2 AG 7
      .ag.ag8
        %h2 AG 8
      .ag.ag9
        %h2 AG 9
      .ag.ag10
        %h2 AG 10

  .ag.ag3
    %h2 AG 3

app/views/home/index.html.haml
#home-hero-area

#home-content
  .container
    .col1
      %h2 left nav
    .col2
      %h1= t 'views.home.h1'
      %h2 middle
      .icon-bubbles4
    .col3
      %h2 right nav
  .container
    .col1
      %h2 left nav
    .col2
      %h1= t 'views.home.h1'
      %h2 middle
      .icon-bubbles4
    .col3
      %h2 right nav
  .container
    .col1
      %h2 left nav
    .col2
      %h1= t 'views.home.h1'
      %h2 middle
      .icon-bubbles4
    .col3
      %h2 right nav
#home-content-wide
  .container
    .col6
      full row six
    .col62
      full row six last
    .col1
      %h2 left nav wide
    .col2
      %h1= t 'views.home.h1'
      %h2 middle
      .icon-bubbles4
    .col3
      %h2 right nav wide

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %link{:rel => "dns-prefetch", :href => "//d3ng1ewoxzx77l.cloudfront.net"}
    %link{:rel => "dns-prefetch", :href => "//www.google-analytics.com"}
    %link{:rel => "dns-prefetch", :href => "//www.googletagmanager.com"}
    %link{:rel => "dns-prefetch", :href => "//sjrtp2.marketo.com"}
    %link{:rel => "dns-prefetch", :href => "//www.bizographics.com"}
    %link{:rel => "dns-prefetch", :href => "//beacon-3.newrelic.com"}
    %link{:rel => "dns-prefetch", :href => "//ib.adnxs.com"}
    %link{:rel => "dns-prefetch", :href => "//ajax.googleapis.com"}
    %link{:rel => "dns-prefetch", :href => "//t.co"}
    %link{:rel => "dns-prefetch", :href => "//pixel.captora.com"}
    %link{:rel => "dns-prefetch", :href => "//stats.g.doubleclick.net"}
    %link{:rel => "dns-prefetch", :href => "//www.googleadservices.com"}
    %link{:rel => "dns-prefetch", :href => "//fonts.googleapis.com"}
    %link{:rel => "dns-prefetch", :href => "//colodin.s3.amazonaws.com"}
    %link{:rel => "dns-prefetch", :href => "//munchkin.marketo.net"}
    = display_meta_tags
    = csrf_meta_tags
    %meta{:content => 'width=device-width, initial-scale=1', :name => 'viewport'}
    %style{:type => "text/css"}
      = Rails.application.assets.find_asset("#{params[:controller]}.css").to_s.html_safe
    = favicon_link_tag 'global/favicon.ico'
  %body
    %noscript
      %iframe{:src => '//www.googletagmanager.com/ns.html?id=GTM-NN47KX', :width => '0', :height => '0', :style => 'display:none;visibility:hidden'}
    %script
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-NN47KX');
    = render 'shared/header'
    #site-content
      = yield
    = render 'shared/footer'
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'

app/views/presses/_form.html.haml
= form_for (@press), :html => { :multipart => true } do |f|
  - if @press.errors.any?
    #error_explanation
      %h2= "#{pluralize(@press.errors.count, "error")} prohibited this press from being saved:"
      %ul
        - @press.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :summary
    = f.text_field :summary
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :logo
    = f.file_field :logo
    = f.hidden_field :logo_image_name
  .actions
    = f.submit 'Save'

app/views/presses/edit.html.haml
%h1 Editing press

= render 'form'

= link_to 'Show', @press
\|
= link_to 'Back', presses_path

app/views/presses/index.html.haml
%h1 Listing presses

%table
  %thead
    %tr
      %th Title
      %th Summary
      %th Url
      %th
      %th
      %th
      
  %tbody
    - @presses.each do |press|
      %tr
        %td= press.title
        %td= press.summary
        %td= press.url
        %td= cl_image_tag("press/" + press.logo_image_name, :width => 80, :crop => :scale)
        %td= link_to 'Show', press
        %td= link_to 'Edit', edit_press_path(press)
        %td= link_to 'Destroy', press, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Press', new_press_path

app/views/presses/new.html.haml
%h1 New press

= render 'form'

%a{:href => '#', :id => 'click_test'}
  tester
%br
%br

= link_to 'Back', presses_path

app/views/presses/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @press.title
%p
  %b Summary:
  = @press.summary
%p
  %b Url:
  = @press.url
= link_to 'Edit', edit_press_path(@press)
\|
= link_to 'Back', presses_path

app/views/resources/index.html.haml
#content-area
  .container
    .full-row
      %h1 Board of Directors

app/views/shared/_footer.html.haml
%footer
  #top-footer-links
    .container
      .footer-search
        %form{:id => 'footer-search-form', :class => 'search-form', :method => 'get', :action => 'http://www.solidfire.com/search-results'}
          %label{:for => 'query-footer'}
          %input{:id => 'query', :class => 'nav-search', :type => 'text', :placeholder => 'Search', :name => 'q'}
      #footer-column-wrapper
        #footer-column-container
          .col1
            %div.column-widths
              %h3 Storage System
              %ul
                %li
                  = link_to 'Storage System Overview', '/storage-system/'
                %li
                  = link_to 'Scale-Out', '/storage-system/scale-out/'
                %li
                  = link_to 'Guaranteed Performance', '/storage-system/guaranteed-performance/'
                %li
                  = link_to 'QoS Benchmark', '/storage-system/qos-benchmark/'
                %li
                  = link_to 'Automated Management', '/storage-system/automated-management/'
                %li
                  = link_to 'High Availability', '/storage-system/high-availability/'
                %li
                  = link_to 'In-Line Efficiency', '/storage-system/in-line-efficiency/'
                %li
                  = link_to 'Product Specifications', '/storage-system/product-specifications/'
                %li
                  = link_to 'Competitive Comparisons', '/storage-system/competitive-comparisons/'
          .col2
            %div.column-widths
              %h3 Solutions
              %ul
                %li
                  = link_to 'Solutions Overview', '/solutions/'
                %li
                  = link_to 'Cloud Orchestration', '/solutions/cloud-orchestration/'
                %li
                  = link_to 'Database', '/solutions/database/'
                %li
                  = link_to 'VDI', '/solutions/vdi/'
                %li
                  = link_to 'VMware Solutions', '/solutions/vmware-solutions/'
                %li
                  = link_to 'Agile Infrastructure', '/solutions/agile-infrastructure/'
                %li
                  = link_to 'Data Protection', '/solutions/data-protection/'
                %li
                  = link_to 'Service Providers', '/solutions/service-providers/'
          .col3
            %div.column-widths

              %h3 Resources
              %ul
                %li
                  = link_to 'Resources Overview', '/resources/'
                %li
                  = link_to 'Documentation', '/resources/?type=Resource-Document'
                %li
                  = link_to 'Videos', '/resources/?type=Resource-Video'
                %li
                  = link_to 'Case Studies', '/resources/?suggestion=025e670d-a7a0-4a00-aa39-4de67f9be47b'
                %li
                  = link_to 'Webinars', '/about/webinars/'
                %li
                  = link_to 'Events', '/about/events/'
                %li
                  = link_to 'Newsletter', '/about/newsletter/'
              .additional-resources
                %h3 Additional Resources
                %ul
                  %li
                    = link_to 'Blog', '/blog'
                  %li
                    = link_to 'Support', '/support'
                  %li
                    = link_to 'Contact Us', '/contact/'
                  %li
                    = link_to 'How to Buy', '/get-started/'
          .col4
            %div.column-widths
              %h3 Company
              %ul
                %li
                  = link_to 'Company Overview', '/about/'
                %li
                  = link_to 'News', '/about/news/'
                %li
                  = link_to 'Press Releases', '/about/press-releases/'
                %li
                  = link_to 'Analyst Reviews', '/about/analyst-reviews/'
                %li
                  = link_to 'Customers', '/about/customers/'
                %li
                  = link_to 'Channel Partners', '/about/channel-partners/'
                %li
                  = link_to 'Technology Partners', '/about/technology-partners/'
                %li
                  = link_to 'Management', '/about/management/'
                %li
                  = link_to 'Board', '/about/board/'
                %li
                  = link_to 'Investors', '/about/investors/'
                %li
                  = link_to 'Careers', '/about/careers/'
  #bottom-section
    .container
      .ft-btm-col1
        .logo
      .ft-btm-col2
        #social-wrapper
          .social-container
            = link_to 'Twitter', 'https://twitter.com/solidfire', :target => '_blank', :class => 'twitter', :title => 'Twitter'
          = link_to 'Linkedin', 'https://www.linkedin.com/company/solidfire-inc.', :target => '_blank', :class => 'linkedin', :title => 'Linkedin'
          = link_to 'Google +', 'https://plus.google.com/+Solidfire/posts', :target => '_blank', :class => 'gplus', :title => 'Google +'
          = link_to 'Facebook', 'https://www.facebook.com/SolidFire', :target => '_blank', :class => 'facebook', :title => 'Facebook'
      .ft-btm-col3
        = link_to 'Terms', '/terms'
        +
        = link_to 'Privacy', '/legal/privacy'
        &copy;
        = Time.now.year